<?php

namespace App\Controller;

use App\Entity\Genre;
use App\Entity\Media;
use App\Form\MediaType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class MediaController extends Controller
{
    /**
     * @Route("/admin/media/{id}", name="media", requirements={"id":"\d+"})
     */
    public function listMedia($id, EntityManagerInterface $em) {
        $medias =$em->getRepository(Media::class)->findBy(['genre'=>$id]);

        return $this->render('media/list.html.twig', [
            'medias' => $medias
        ]);
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

    /**
     * @Route("/admin/media/create", name="media_create")
     */
    public function create(Request $request, EntityManagerInterface $em) {
        $media = new Media();
        $mediaForm = $this->createForm(MediaType::class, $media);
        $utilisateur = $this->getUser();
        $mediaForm->handleRequest($request);
        if($mediaForm->isSubmitted() && $mediaForm->isValid()) {
            $media->setUtilisateurs($utilisateur);
            $file = $mediaForm->get('picture')->getData();
            $filename = $this->generateUniqueFileName().'.'.$file->guessExtension();
            $ext = $file->guessExtension();

            // Move the file to the directory where brochures are stored
            try {
                $file->move(
                    $this->getParameter('file_directory'),
                    $filename
                );
            } catch (FileException $e) {
                // ... handle exception if something happens during file upload
            }
            $media->setPicture($filename);
            $media->setExtension($ext);

            $em->persist($media);
            $em->flush();

            $this->addFlash('success', 'Media successfully added!');

            $genreofMedia = new Genre();
            $genreofMedia = $media->getGenre();
            return $this->redirectToRoute('media', array('id' => $genreofMedia->getId()));
        }

        return $this->render('media/add.html.twig', [
            'MediaForm' => $mediaForm->createView()
        ]);
    }




        /**
     * @Route("/admin/media/update/{id}", name="media_update", requirements={"id":"\d+"})
     */
    public function update(Media $media, Request $request, EntityManagerInterface $em) {
        $media->setPicture(
            new File($this->getParameter('file_directory').'/'.$media->getPicture())
        );
        $mediaForm = $this->createForm(MediaType::class, $media);
        $mediaForm->handleRequest($request);

        if($mediaForm->isSubmitted() && $mediaForm->isValid()) {
            $em->persist($media);
            $em->flush();

            $this->addFlash('success', 'Media successfully update!');
            $genreofMedia = new Genre();
            $genreofMedia = $media->getGenre();
            return $this->redirectToRoute('media', array('id' => $genreofMedia->getId()));
        }

        return $this->render('media/add.html.twig', [
            'MediaForm' => $mediaForm->createView()
        ]);
    }

    /**
     * @Route("/admin/media/delete", name="media_delele_default", defaults={"id":0})
     * @Route("/admin/media/delete/{id}", name="media_delete", requirements={"id":"\d+"})
     */
    public function delete(EntityManagerInterface $em, Media $media) {
        if(count($media->getIdeas()) > 0){
            $this->addFlash('error', "You can't delete this media!!");
            return $this->redirectToRoute('media');
        }

        $em->remove($media);
        $em->flush();
        $this->addFlash("success", "Media successfully deleted!");
        return $this->redirectToRoute("media");
    }
}
